# Generated by Django 3.0.6 on 2020-06-04 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='emp',
            table='Emp',
        ),
    ]
