# Generated by Django 3.0.6 on 2020-10-28 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0002_auto_20200604_1133'),
    ]

    operations = [
        migrations.CreateModel(
            name='movieId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieId', models.ImageField(upload_to='')),
                ('titles', models.CharField(max_length=500)),
                ('geners', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'movie',
            },
        ),
    ]
